title: Victor Mazeli # your name (or website title) here
logo: "/images/IMG_20200617_154453_972.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  i am full stack developer, i build web applications and mobile applications, that meets buisness needs and requirements.
  i am available and ready to work on any solutions or projects. 
  My skills are:
  - Frontend: HTML, CSS, JAVASCRIPT
  - Backend: PHP Programing language.
  - Git
  - Docker
  - Mobile Application Developemnt
  - Libaries/frameworks: Vue, Laravel, Flutter.
  - Others: Python programing language, Dart.
  Any further questions? please feel free to reach me on my social media handles.
  
  
  
  
  
  
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
